source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'

gem 'rake'
gem 'sqlite3'

gem 'opal-router',    github: 'adambeynon/opal-router'
gem 'hyalite'
gem 'menilite'

gem 'gohra', path: '../..'

gem 'haml'
gem 'sass'

gem 'sinatra-websocket'
gem 'bcrypt'
