source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'

gem 'rake'
gem 'sqlite3'

gem 'opal-router',    github: 'adambeynon/opal-router'
gem 'hyalite', path: '../../../../../hyalite'
gem 'menilite', path: '../../../../../menilite'

gem 'haml'
gem 'sass'

gem 'bcrypt'
